### ISSUE TITLE
No gate on first beat in Digital Sequencer

### ISSUE THREAD

**Issue by Revheim** [clone45/voxglitch#47]
On the first beat, and on a reset I don't get any gate signal coming out.

**Comment by clone45** [comment]
Thanks for the bug report!  I'll take a peek asap.

**Comment by clone45** [comment]
Ok, I fixed this and merged it into the master branch.  I'll try to get a new version which includes this bugfix published in the next few days.

**Comment by Revheim** [comment]
Awesome, I'll compile and test now.

**Comment by Revheim** [comment]
Still not getting the first one to fire :/ Anyway I can send you a patch for demonstration?

**Comment by clone45** [comment]
Of course!  I was able to recreate your issue when testing yesterday.  Please send over the patch and I'll definitely check it out.

**Comment by Revheim** [comment]
I just added a txt extension so I could upload here. In the patch, the bass drum is the most obvious to catch, it's being triggered from sequence four. I have also added a gate-seq-64 with the same pattern, if you move the cable from digital sequencer 4, and instead take the output from gate-seq-64 the first beat is heard.
[notriggerfirstbeat.vcv.txt](https://github.com/clone45/voxglitch/files/4529847/notriggerfirstbeat.vcv.txt)

**Comment by clone45** [comment]
How strange!  I swore that my fix worked, but now it's definitely not working.  Ha ha ha.  I'm just starting my day job but I'll revisit this tonight.  Thank for sending over that patch!

**Comment by clone45** [comment]
Wait... I spoke too soon.  I hadn't pulled down the most recent version.  Everything looks ok to me.  I wasn't able to use your exact patch because I was missing some of the modules.  But I did recreate the basics and recorded a video for you.  https://youtu.be/SP-NTnCEQJA.  Take a peek and let me know what you think.  :-)

**Comment by Revheim** [comment]
I'm getting the first gate coming through from sequence number 1, but only from number 1..? In this patch I've hooked the bass drum to number 4, and it's missing it's first beat. I added another Digital Sequencer, and recreated the gate-pattern in 1 and 2 in that one, and it works only from number one. It seems it's only sequence 1 that outputs the first gate...

**Comment by clone45** [comment]
Oh ... yeah.  That makes sense.  I goofed up on that one.  I'll get it fixed asap, but that may be tonight.  I'll keep you posted.

**Comment by Revheim** [comment]
Awesome, and thanks for the quick response, thats really great :)

**Comment by clone45** [comment]
Ok!  I'm hoping that this last round of edits will do the trick.  I tested in a few different scenarios and it appears to be OK now.  Can you give it a shot?

**Comment by Revheim** [comment]
Sorry for the late reply, been a busy day. 
I just recompiled now, and so far it seems to work just as expected! Brilliant stuff, really loving this sequencer. 
Thanks for fixing everything so quickly :)
